# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyComic' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyComic
  pod 'HanekeSwift'

  target 'MyComicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyComicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
